services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: [ "sh", "-c", "npm install && npm run dev --workspace apps/web -- --hostname 0.0.0.0" ]
