FROM node:20-alpine AS build
WORKDIR /app
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY .eslintrc.cjs .prettierrc ./
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
RUN pnpm install --frozen-lockfile || pnpm install
RUN pnpm --filter @blaze/web build

FROM node:20-alpine AS serve
WORKDIR /srv
COPY --from=build /app/apps/web/dist ./dist
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm add -g serve
EXPOSE 4173
CMD [ "serve", "-s", "dist", "-l", "4173" ]
