[build]
  command = "cp final-deployed-site.html index.html"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'"
    Permissions-Policy = "camera=(self), microphone=(self), geolocation=()"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
