[build]
  command = "npm run build --workspace apps/web"
  publish = "apps/web/.next"

[[headers]]
  for = "/dev/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
