name = "blazesportsintel-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "blazesportsintel-api-production"
route = { pattern = "api.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "blazesportsintel-api-staging"
route = { pattern = "staging-api.blazesportsintel.com/*", zone_name = "blazesportsintel.com" }
vars = { ENVIRONMENT = "staging" }

# KV Namespaces for caching
[[kv_namespaces]]
binding = "SPORTS_KV"
id = "sports_cache"
preview_id = "sports_cache_preview"

# R2 Storage for media/data
[[r2_buckets]]
binding = "R2_STORAGE"
bucket_name = "blazesportsintel-data"

# D1 Database for structured data
[[d1_databases]]
binding = "DB"
database_name = "blazesportsintel"
database_id = "blazesportsintel-db"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "AE"
dataset = "blazesportsintel_analytics"

# Rate limiting
[limits]
cpu_ms = 50
subrequests = 50

# Development settings
[dev]
port = 8787
local_protocol = "http"