name: Daily Sports Data Refresh
on:
  schedule:
    - cron: '0 14,20 * * *'  # 9:00 AM & 3:00 PM US Central
  workflow_dispatch: {}
  
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: 
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Create data directories
        run: |
          mkdir -p data/{nfl,mlb,ncaa_fb,college_bb,tx_hs_fb,pg_tx}
          mkdir -p .cache
          
      - name: Refresh all league data
        run: pnpm run refresh:all
        
      - name: Validate data
        run: pnpm run validate || echo 'Validation warnings (non-blocking)'
        
      - name: Commit data updates
        run: |
          git config user.name 'blaze-bot'
          git config user.email 'bot@blazesportsintel.com'
          git add -A data/ .cache/
          git diff --staged --quiet || git commit -m "chore(data): refresh $(date -u +%F) [automated]"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'chore(data): daily refresh $(date +%F)'
          branch: 'chore/daily-refresh-$(date +%F)'
          body: |
            ## 🔄 Automated Data Refresh
            
            **Date:** $(date)
            
            Updated data for all leagues:
            - NFL teams and standings
            - MLB teams and rosters
            - Texas HS Football powerhouse programs
            - Perfect Game TX tournaments
            - NCAA Football FBS programs
            - College Baseball programs
            
            🤖 Generated by BlazeSportsIntelBot
